### ISSUE TITLE
images en double résolution

### ISSUE THREAD

**Issue by Fil** [severo/portfolios-redcartografica#10]
Actuellement le système produit des images 300x200 on voudrait des 600x400

**Comment by severo** [comment]
Oui, il faut travailler la gestion des images, j'ai pas creusé. Pour un site de portfolios, c'est important de faire ça bien, éventuellement avec une image qui dépendende du media-query

**Comment by Fil** [comment]
je viens de mettre 600x400 dans le squelette à la place de 300x200 et d'un
seul coup tout ce qui était "flou" sur mon écran retina est devenu super
net. Je pense pas que ce soit la peine d'optimiser à mort, ça reste des
petites images :)

-- Fil

**Comment by severo** [comment]
Faut refaire les deux images placeholder alors... Elles sont en 200x300. On pourrait plutôt faire des SVG d'ailleurs. Je m'en charge.

**Comment by severo** [comment]
Je m'en chargeRAI lundi

**Comment by severo** [comment]
Closed by https://github.com/severo/theme-hugo-redcartografica/commit/65584d77187d45eb1894b8bc33741ee75ea7295f
