### ISSUE TITLE
passer à la ligne après la personCard ?

### ISSUE THREAD

**Issue by Fil** [severo/portfolios-redcartografica#12]
j'essaie de voir comment mieux occuper l'espace

l'idée est qu'on commence par la personne, puis ses "œuvres", et on termine par un bloc qui signifie "si vous voulez travailler avec moi, n'hésitez pas à me contacter etc".

**actuel**
<img width="421" alt="actuel" src="https://user-images.githubusercontent.com/7001/37864863-9a69e1e6-2f74-11e8-9715-ddb3ba617d9c.png">

**proposé**
<img width="430" alt="propose copie" src="https://user-images.githubusercontent.com/7001/37864869-b34e22b2-2f74-11e8-8a95-66ee2c4ba887.png">

**Comment by severo** [comment]
Oui, ça sera plus clair, tu as raison. Sinon on ne comprend pas nécessairement la différence entre la personcard et la card.
Et oui, il manque une section pour les contacts. L'autre solution plus classique c'est une colonne pour la personne et les contacts, et las cards dans le reste de la page.
