### ISSUE TITLE
j'aime pas le logo du lien

### ISSUE THREAD

**Issue by Fil** [severo/portfolios-redcartografica#2]
c'est une chaîne qui enchaîne et cadenasse :)
<img width="141" alt="capture d ecran 2018-03-24 a 09 36 49" src="https://user-images.githubusercontent.com/7001/37862035-e7db8408-2f46-11e8-8041-6b0714252bfb.png">

un globe ? bof
une maison (home page) ? bof
un rond (type logo firefox/chrome, peut-être yin yang) ?

**Comment by Fil** [comment]
J'aime bien fa-social-home https://forkawesome.github.io/Fork-Awesome/icon/social-home/

à voir s'il y a mieux — ensuite on généralise
<img width="204" alt="capture d ecran 2018-03-24 a 10 03 59" src="https://user-images.githubusercontent.com/7001/37862292-b56f4ffa-2f4a-11e8-9fda-2e74631bf90a.png">

**Comment by Fil** [comment]
ah je m'aperçois que social-home c'est pas une image générique, c'est lié à un site et une marque https://socialhome.network/ :(

**Comment by Fil** [comment]
fa-address-book-o est ok aussi
<img width="330" alt="capture d ecran 2018-03-24 a 10 40 17" src="https://user-images.githubusercontent.com/7001/37862584-c41a9d3e-2f4f-11e8-9a4d-80cf1c26d8fb.png">

**Comment by severo** [comment]
C'est le souci, il n'y a pas vraiment d'icône pour dire "site web personnel / générique"

**Comment by severo** [comment]
OK, on ferme, que chacun cherche l’icône qu'il veut
