### ISSUE TITLE
ouvrir les références dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by Fil** [severo/portfolios-redcartografica#3]
dans notre cas je crois que c'est justifié

**Comment by Fil** [comment]
j'ai tenté de faire la modif (pas de problème :)) mais ensuite je ne peux pas la pusher

```
remote: Permission to severo/theme-hugo-redcartografica.git denied to Fil.
fatal: unable to access 'https://github.com/severo/theme-hugo-redcartografica/': The requested URL returned error: 403
```

(je crois que je ne sais pas utiliser les submodules)

le patch:
https://gist.github.com/Fil/74981b7282e5d4d2bf2d5166653f4d88

**Comment by severo** [comment]
Non, j'ai juste oublié de te donner les droits de commit pour le thème

**Comment by severo** [comment]
N'oublie pas d'actualiser le dépôt git du site avec la reference de la nouvelle version du thème pour que ça soit pris en compte et déployé automatiquement.

**Comment by Fil** [comment]
pas compris

-- Fil

**Comment by severo** [comment]
Quand tu fais un commit dans le submodule, et ensuite tu remontes dans l'arborescence pour te trouver dans le projet parent (portfolios), si tu fais `git status`, tu verras qu'il propose un changement de référence pour le submodule du thème. Il faut faire git add -p, par exemple, pour ajouter ce changement, c'est à dire mettre à jour la dépendance du projet envers son thème, et git commit pour intégrer ce changement de version du thème dans le site. Normalement quand tu push vers github, le site devrait se déployer tout seul.

**Comment by Fil** [comment]
Je pense qu'il me manque une info : il se déploie où ?

**Comment by severo** [comment]
Sur mon serveur, qui écoute les webhooks envoyés par github à chaque push qu'il reçoit.
