### ISSUE TITLE
un paragraphe de texte sous la fiche perso ?

### ISSUE THREAD

**Issue by Fil** [severo/portfolios-redcartografica#5]
ou juste une ligne … mais ça pose la question du multilinguisme #4

**Comment by severo** [comment]
C'est pas un souci, le multilinguisme. Il faut bien choisir une langue de toute manière, choisir la langue par défaut à l'arrivée sur le site, gérer la navigation.

**Comment by Fil** [comment]
J'ai essayé d'ajouter `description: "tada"` dans ma personCard mais ça n'est pas pris en compte ; il faut que je lise la doc de hugo :)

**Comment by severo** [comment]
Il faut que tu modifies le template personCard dans le thème, pour ajouter le code HTML que tu veux. C'est très facile, on dirait des squelettes SPIP
